dev:
  host: http://192.168.28.139:8080
  mysql:
#    address: rm-cn-nwy3aocn0000pho.rwlb.rds.aliyuncs.com
    address: localhost
#    username: abstyle
    username: root
#    password: Fastdeer123
    password: 12345678
  redis:
#    host: r-bp15xrn4toitsx8rgxpd.redis.rds.aliyuncs.com
    host: 127.0.0.1
    password: Fastdeer123
    database:
      user-db: 0
      message-db: 1
    port: 6379
    maxTotal: 30 # 最大连接数
    maxIdle: 20 # 最大空闲连接数

#  staticUrl: file:/usr/local/lib/fastdeer-end/src/main/resources/static/ # Linux
  staticUrl: file:/Users/wang/Documents/Idea_project/fastdeer-end/src/main/resources/static/ # Mac
#  staticUrl: file:F:\FastDeer\FastDeer-End\src\main\resources\static\ # Win
  maxFileSize: 200
  maxRequestSize: 400
  avatarUpload:
#    uploadLocation: /usr/local/lib/fastdeer-end/src/main/resources/static/avatar/
#    uploadLocation: /Users/wang/Documents/Idea_project/fastdeer-end/src/main/resources/static/avatar/ # Mac
    uploadLocation: F:\FastDeer\FastDeer-End\src\main\resources\static\avatar\
    avatarUrl: ${dev.host}/static/avatar/
  postUpload:
#    uploadLocation: /usr/local/lib/fastdeer-end/src/main/resources/static/post/ #Linux
    uploadLocation: /Users/wang/Documents/Idea_project/fastdeer-end/src/main/resources/static/post/ # Mac
#    uploadLocation: F:\FastDeer\FastDeer-End\src\main\resources\static\post\ # Win
    postUrl: ${dev.host}/static/post/

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${dev.mysql.address}:3306/fast_deer?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dev.mysql.username}
    password: ${dev.mysql.password}


fastDeer:
  jwt:
    secret: fastDeer8888 # Spring Security 密钥
    expireTime: 120 # token过期时间， 单位-分钟
    issuer: fast-deer # JWT签发者
  admin:
    username: user
    password: 123

# 设计安全考虑，不使用配置文件+accessKeyId和accessKeySecret，使用服务器环境变量。因此服务器需要环境变量中分别暴露：
# export OSS_ACCESS_KEY_ID=
# export OSS_ACCESS_KEY_SECRET=
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com/
  bucketName: fast-deer